/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuildOffRouteImport } from './routes/build-off'
import { Route as IndexRouteImport } from './routes/index'

const BuildOffRoute = BuildOffRouteImport.update({
  id: '/build-off',
  path: '/build-off',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build-off': typeof BuildOffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build-off': typeof BuildOffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build-off': typeof BuildOffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/build-off'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/build-off'
  id: '__root__' | '/' | '/build-off'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildOffRoute: typeof BuildOffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/build-off': {
      id: '/build-off'
      path: '/build-off'
      fullPath: '/build-off'
      preLoaderRoute: typeof BuildOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildOffRoute: BuildOffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
