/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BuildOffRouteImport } from './routes/build-off'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildOffOperatorRouteImport } from './routes/build-off.operator'
import { Route as ApiSaceCompleteRouteImport } from './routes/api/sace/complete'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiBadgeCategoryRankToolRouteImport } from './routes/api/badge/$category/$rank/$tool'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildOffRoute = BuildOffRouteImport.update({
  id: '/build-off',
  path: '/build-off',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildOffOperatorRoute = BuildOffOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => BuildOffRoute,
} as any)
const ApiSaceCompleteRoute = ApiSaceCompleteRouteImport.update({
  id: '/api/sace/complete',
  path: '/api/sace/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgeCategoryRankToolRoute =
  ApiBadgeCategoryRankToolRouteImport.update({
    id: '/api/badge/$category/$rank/$tool',
    path: '/api/badge/$category/$rank/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build-off': typeof BuildOffRouteWithChildren
  '/demo': typeof DemoRoute
  '/partners': typeof PartnersRoute
  '/build-off/operator': typeof BuildOffOperatorRoute
  '/api/sace/complete': typeof ApiSaceCompleteRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/badge/$category/$rank/$tool': typeof ApiBadgeCategoryRankToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build-off': typeof BuildOffRouteWithChildren
  '/demo': typeof DemoRoute
  '/partners': typeof PartnersRoute
  '/build-off/operator': typeof BuildOffOperatorRoute
  '/api/sace/complete': typeof ApiSaceCompleteRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/badge/$category/$rank/$tool': typeof ApiBadgeCategoryRankToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build-off': typeof BuildOffRouteWithChildren
  '/demo': typeof DemoRoute
  '/partners': typeof PartnersRoute
  '/build-off/operator': typeof BuildOffOperatorRoute
  '/api/sace/complete': typeof ApiSaceCompleteRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/badge/$category/$rank/$tool': typeof ApiBadgeCategoryRankToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build-off'
    | '/demo'
    | '/partners'
    | '/build-off/operator'
    | '/api/sace/complete'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/badge/$category/$rank/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build-off'
    | '/demo'
    | '/partners'
    | '/build-off/operator'
    | '/api/sace/complete'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/badge/$category/$rank/$tool'
  id:
    | '__root__'
    | '/'
    | '/build-off'
    | '/demo'
    | '/partners'
    | '/build-off/operator'
    | '/api/sace/complete'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/badge/$category/$rank/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildOffRoute: typeof BuildOffRouteWithChildren
  DemoRoute: typeof DemoRoute
  PartnersRoute: typeof PartnersRoute
  ApiSaceCompleteRoute: typeof ApiSaceCompleteRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiBadgeCategoryRankToolRoute: typeof ApiBadgeCategoryRankToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-off': {
      id: '/build-off'
      path: '/build-off'
      fullPath: '/build-off'
      preLoaderRoute: typeof BuildOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-off/operator': {
      id: '/build-off/operator'
      path: '/operator'
      fullPath: '/build-off/operator'
      preLoaderRoute: typeof BuildOffOperatorRouteImport
      parentRoute: typeof BuildOffRoute
    }
    '/api/sace/complete': {
      id: '/api/sace/complete'
      path: '/api/sace/complete'
      fullPath: '/api/sace/complete'
      preLoaderRoute: typeof ApiSaceCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badge/$category/$rank/$tool': {
      id: '/api/badge/$category/$rank/$tool'
      path: '/api/badge/$category/$rank/$tool'
      fullPath: '/api/badge/$category/$rank/$tool'
      preLoaderRoute: typeof ApiBadgeCategoryRankToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BuildOffRouteChildren {
  BuildOffOperatorRoute: typeof BuildOffOperatorRoute
}

const BuildOffRouteChildren: BuildOffRouteChildren = {
  BuildOffOperatorRoute: BuildOffOperatorRoute,
}

const BuildOffRouteWithChildren = BuildOffRoute._addFileChildren(
  BuildOffRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildOffRoute: BuildOffRouteWithChildren,
  DemoRoute: DemoRoute,
  PartnersRoute: PartnersRoute,
  ApiSaceCompleteRoute: ApiSaceCompleteRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiBadgeCategoryRankToolRoute: ApiBadgeCategoryRankToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
