
ALTER TABLE public.build_off_runs
  ADD COLUMN IF NOT EXISTS fidelity SMALLINT,
  ADD COLUMN IF NOT EXISTS correctness SMALLINT,
  ADD COLUMN IF NOT EXISTS refactor SMALLINT,
  ADD COLUMN IF NOT EXISTS honesty SMALLINT,
  ADD COLUMN IF NOT EXISTS cost_cents INTEGER,
  ADD COLUMN IF NOT EXISTS bundle_kb INTEGER,
  ADD COLUMN IF NOT EXISTS judge_notes TEXT;
